### PR TITLE
Redux and lazy loading

### PR DESCRIPTION
**Pull request by xkevinle**
- Implement apiReducer for Redux for storing cluster data and metrics
- Utilized re-render mechanics for refresh and favorite button
- Lazy loading also implemented

### CODE REVIEW

**Comment by murad-alqadi** [comment]
- Huge progress here. Can limit expensive calls and access single store of truth for cluster metrics.

**Review by murad-alqadi — APPROVED** [review]
Redux implementation almost complete

**Comment by irvinie** [comment]
Tested and prop-drill removal failed to induce bugs, need to complete redux

**Review by irvinie — COMMENTED** [review]
Tested and prop-drill removal failed to induce bugs, need to complete redux

**Pull request merged**
