### PR TITLE
VaaS 4.0

### PR DESCRIPTION
**Pull request by StevenCYTong**
VaaS 4.0 - merge to main

### CODE REVIEW

**Review by greyali — APPROVED** [review]
LGTM. Solid work.

**Review by DankWolf — APPROVED** [review]
Looks good

**Review by johannamerluza — APPROVED** [review]

**Review by DankWolf — APPROVED** [review]

**Review by johannamerluza — APPROVED** [review]

**Review by Terinss — APPROVED** [review]
great work!

**Comment by murad-alqadi** [comment]
Love to see testing. Great work everyone!

**Pull request merged**
